### ISSUE TITLE
Player selects difficulty, with approximate word lengths for each tier.

### ISSUE THREAD

**Issue by dsberger** [code-newbies/js-tuesday-hangman#10]
Question to think about: Are short words harder or easier than long words?

**Comment by coryunderwood** [comment]
Depends, how many people have seen the word Qi used in a sentence.

**Comment by krantzinator** [comment]
I have not seen it in a sentence, but it comes up often in Bananagrams.

**Comment by krantzinator** [comment]
Advanced: rate difficulty of words based on how commonly they are used.

**Comment by dsberger** [comment]
Transferred to Trello.
