### ISSUE TITLE
Create scaffold of layout for other team members to build on.

### ISSUE THREAD

**Issue by dsberger** [code-newbies/js-tuesday-hangman#28]

**Comment by marcusp619** [comment]
I have scaffold out the webapp using yeoman. Im wondering if anyone else would like to work with this as well. If not i can just add the boilerplate info to the html file. 

Here is some info on yeoman. 

http://yeoman.io/
and
https://www.youtube.com/watch?v=gKiaLSJW5xI

**Comment by nannigan** [comment]
good idea, it would be cool to see what you have.

**Comment by marcusp619** [comment]
I accidentally pushed it to the master, once I get off work today I'll figure out how to undo the commit when I get off. If everyone understands it I'll just leave it. The files we are workin on currently are all in the app folder I made the main page a mini guide
