### ISSUE TITLE
alpha-keypad no longer fades out used letters

### ISSUE THREAD

**Issue by krantzinator** [code-newbies/js-tuesday-hangman#34]
For our id='alphabet-keypad' item, the letters no longer fade to gray once they have been clicked with the most recent version I forked. Are other people having this issue as well?

**Comment by dsberger** [comment]
I notice the same thing.

**Comment by simon-xiong-ca** [comment]
index.html was calling "styles.js" instead of "scripts.js" for some reason so that's probably why it wasn't working. I'll look into it.

**Comment by dsberger** [comment]
Transferred to Trello.
