### ISSUE TITLE
Improve outdated browser support

### ISSUE THREAD

**Issue by coryunderwood** [code-newbies/js-tuesday-hangman#35]
Currently, index.html uses IE conditional brackets (approx line 20) to test for things lowerthan IE 10.   These are ignored by most browsers, and do not support graceful degradation.

Consider other options, explore which parts of the codebase will not perform on older clients, and evaluate a method for either supporting them, or letting them know the site won't work.   Must be cross-browser compatible.

**Comment by dsberger** [comment]
Transferred to Trello (as speculative).
