### ISSUE TITLE
Create the graveyard of letters that have been played but are not in the word.

### ISSUE THREAD

**Issue by dsberger** [code-newbies/js-tuesday-hangman#4]

**Comment by valkyrea** [comment]
Hey Piecedigital, I am not sure what you are designing, but if you'd like, I could share what I've been working on so far for the letter graveyard.  I got this idea of making little tombstones and maybe have the letters have some red blood letters.  Let me know what you think.

**Comment by piecedigital** [comment]
@valkyrea I like the idea, though I'd like to see how the page has been designed first. I'd rather not have a merge error for HTML or CSS.

**Comment by dsberger** [comment]
Transferred to Trello.
